name: Run Tests

on:
  workflow_call:
    inputs:
      project:
        required: true
        type: string
      report_dir:
        required: true
        type: string
    secrets:
      QA_BASE_URL:
        required: false
      QA_API_BASE_URL:
        required: true
      QA_API_KEY:
        required: true
      QA_API_LOGIN:
        required: true
      QA_API_PASSWORD:
        required: true
      QA_UI_USER:
        required: false
      QA_UI_PASSWORD:
        required: false
      QA_PRACTICE_DOWNLOAD_URL:
        required: false
      QA_PRACTICE_UPLOAD_URL:
        required: false

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    container:
      image: mcr.microsoft.com/playwright:v1.58.2-noble

    steps:
      - uses: actions/checkout@v5

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm run test:ci:${{ inputs.project }}
        env:
          TEST_ENV: qa
          BASE_URL: ${{ secrets.QA_BASE_URL }}
          API_BASE_URL: ${{ secrets.QA_API_BASE_URL }}
          API_KEY: ${{ secrets.QA_API_KEY }}
          API_LOGIN: ${{ secrets.QA_API_LOGIN }}
          API_PASSWORD: ${{ secrets.QA_API_PASSWORD }}
          UI_USER: ${{ secrets.QA_UI_USER }}
          UI_PASSWORD: ${{ secrets.QA_UI_PASSWORD }}
          PRACTICE_DOWNLOAD_URL: ${{ secrets.QA_PRACTICE_DOWNLOAD_URL }}
          PRACTICE_UPLOAD_URL: ${{ secrets.QA_PRACTICE_UPLOAD_URL }}

      - name: Upload Playwright HTML report
        if: always()
        uses: actions/upload-artifact@v5
        with:
          name: ${{ inputs.project }}-playwright-report
          path: playwright-report/
          retention-days: 30

      - name: Deploy Playwright report to GitHub Pages
        if: always()
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: playwright-report/
          destination_dir: ${{ inputs.report_dir }}/${{ github.run_number }}
          keep_files: true
