name: demo

on:
  push:
    branches:
      - main

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - run: npm ci
      - run: npm run lint

  api-tests:
    needs: lint
    uses: ./.github/workflows/run-tests.yml
    with:
      project: api
      report_dir: api
    secrets: inherit

  ui-tests:
    needs: api-tests
    uses: ./.github/workflows/run-tests.yml
    with:
      project: ui
      report_dir: ui
    secrets: inherit

  visual-tests:
    needs: ui-tests
    uses: ./.github/workflows/run-tests.yml
    with:
      project: visual
      report_dir: visual
    secrets: inherit
