name: demo

on:
  push:
    branches:
      - main

jobs:
  api-tests:
    uses: ./.github/workflows/run-tests.yml
    with:
      project: api
      report_dir: api
    secrets: inherit

  ui-tests:
    needs: api-tests
    uses: ./.github/workflows/run-tests.yml
    with:
      project: ui
      report_dir: ui
    secrets: inherit

  visual-tests:
    needs: ui-tests
    uses: ./.github/workflows/run-tests.yml
    with:
      project: visual
      report_dir: visual
    secrets: inherit
